[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vllm-aio"
description = "Custom vLLM ft endpoints"
requires-python = ">=3.10"

dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = "version.txt"}

[project.entry-points."vllm.endpoint_plugins"]
arguments_api = "vllm_arguments_endpoint_plugin:ArgumentsEndpointPlugin"
liveness_api = "vllm_liveness_plugin:LivenessPlugin"
readiness_api = "vllm_readiness_plugin:ReadinessPlugin"
model_instance = "vllm_model_instance_plugin:ModelInstancePlugin"


[tool.setuptools.packages.find]
where = ["plugins"]