name: Check Upstream vLLM Release

on:
  schedule:
    - cron: '0 2 * * *' # Tourne tous les jours à 2h du matin
  workflow_dispatch:

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check official vLLM release and sync
        env:
          GH_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          UPSTREAM_TAG=$(curl -s https://api.github.com/repos/vllm-project/vllm/releases/latest | jq -r .tag_name)
          CLEAN_UPSTREAM="${UPSTREAM_TAG#v}"
          echo "Latest official vLLM tag is: $CLEAN_UPSTREAM"
          
          LOCAL_VLLM_VERSION=$(cat VLLM_VERSION | tr -d '[:space:]')
          LOCAL_VERSION=$(cat version.txt | tr -d '[:space:]')
          echo "Our current vLLM version: $LOCAL_VLLM_VERSION"
          
          if [ "$CLEAN_UPSTREAM" != "null" ] && [ "$CLEAN_UPSTREAM" != "$LOCAL_VLLM_VERSION" ]; then
            echo "Update needed! Proposing a Pull Request..."
            
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            BRANCH_NAME="update-vllm-to-$CLEAN_UPSTREAM"
            git checkout -b "$BRANCH_NAME"
            
            echo "$CLEAN_UPSTREAM" > VLLM_VERSION
            git add VLLM_VERSION

            IFS='.' read -r MAJOR MINOR PATCH <<< "$LOCAL_VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "$NEW_VERSION" > version.txt
            git add version.txt
            
            git commit -m "update: bump vLLM target to $CLEAN_UPSTREAM"
            git push origin "$BRANCH_NAME"
            
            PR_URL=$(gh pr create \
              --title "Update vLLM base image to $CLEAN_UPSTREAM" \
              --body "A new version of vLLM has been released!"\
              --base main \
              --head "$BRANCH_NAME")

            PR_NUMBER=$(basename "$PR_URL")
            echo "PR created: $PR_URL (#$PR_NUMBER)"

            gh pr merge "$BRANCH_NAME" --squash --admin

            gh release create "$NEW_VERSION" \
              --target main \
              --title "$NEW_VERSION" \
              --notes "[#$PR_NUMBER]($PR_URL) : vLLM $UPSTREAM_TAG"
              
          else
            echo "We are up to date."
          fi
